#!/bin/sh

#Remove unnecessary guests additions preinstalled
if [ -e /target/usr/bin/systemd-detect-virt ] && [ -x /target/usr/bin/systemd-detect-virt ]; then

SYSTEMD_CHECK=$(chroot /target systemd-detect-virt || true)
SYS_CHECK=$(cat /sys/class/dmi/id/sys_vendor | cut -d' ' -f1)

mount_fs() {
		mount --bind /sys /target/sys
		mount --bind /proc /target/proc
		mount --bind /dev /target/dev
		mount --bind /dev/pts /target/dev/pts
}

umount_fs() {
		umount /target/sys
		umount /target/proc
		umount /target/dev/pts
		umount /target/dev
}

mount_fs

if [ $SYSTEMD_CHECK = vmware ]; then
	echo "Hypervisor detected: $SYSTEMD_CHECK. Removal of all other guest additions."
	chroot /target apt-get autoremove --purge -y virtualbox-guest-utils virtualbox-guest-x11 xserver-xorg-video-qxl qemu-guest-agent spice-vdagent spice-webdavd hyperv-daemons || true
	chroot /target update-initramfs -u -k all || true

elif [ $SYS_CHECK = innotek ]; then
	echo "Hypervisor detected: $SYS_CHECK (VirtualBox). Removal of all other guest additions."
	chroot /target apt-get autoremove --purge -y open-vm-tools open-vm-tools-desktop xserver-xorg-video-qxl qemu-guest-agent spice-vdagent spice-webdavd hyperv-daemons || true
	chroot /target update-initramfs -u -k all || true

elif [ $SYS_CHECK = QEMU ]; then
	echo "Hypervisor detected: $SYS_CHECK. Removal of all other guest additions."
	chroot /target apt-get autoremove --purge -y virtualbox-guest-utils virtualbox-guest-x11 open-vm-tools open-vm-tools-desktop hyperv-daemons || true
	chroot /target update-initramfs -u -k all || true

elif [ $SYSTEMD_CHECK = microsoft ]; then
	echo "Hypervisor detected: $SYSTEMD_CHECK. Removal of all other guest additions."
	chroot /target apt-get autoremove --purge -y virtualbox-guest-utils virtualbox-guest-x11 open-vm-tools open-vm-tools-desktop xserver-xorg-video-qxl qemu-guest-agent spice-vdagent spice-webdavd || true
	chroot /target update-initramfs -u -k all || true

elif [ $SYSTEMD_CHECK = none ] || [ $SYSTEMD_CHECK = zvm ] || [ $SYSTEMD_CHECK = powervm ] || [ $SYSTEMD_CHECK = xen ] || [ $SYSTEMD_CHECK = bochs ] || [ $SYSTEMD_CHECK = uml ] || [ $SYSTEMD_CHECK = parallels ] || [ $SYSTEMD_CHECK = bhyve ] || [ $SYSTEMD_CHECK = qnx ] || [ $SYSTEMD_CHECK = acrn ]; then
	echo "No hypervisor detected with preinstalled guest additions. Deletion of all guest additions."
	chroot /target apt-get autoremove --purge -y virtualbox-guest-utils virtualbox-guest-x11 open-vm-tools open-vm-tools-desktop xserver-xorg-video-qxl qemu-guest-agent spice-vdagent spice-webdavd hyperv-daemons || true
	chroot /target update-initramfs -u -k all || true
fi
fi

#Check if / use BTRFS as filesystem to remove kaisen-btrfs-snapshots if BTRFS not use
CHECK_ROOTFS=$(grep -v -E "^(#|$)" /target/etc/fstab | grep -v /bin | grep -v /boot | grep -v /etc | grep -v /home | grep -v /lib | grep -v /media | grep -v /mnt | grep -v /opt | grep -v /root | grep -v /run | grep -v /sbin | grep -v /srv | grep -v /tmp | grep -v /usr | grep -v /var | grep -o btrfs || true)

if [ $CHECK_ROOTFS = btrfs ]; then
	echo "BTRFS use in /. No action required."
else
	echo "BTRFS not use in /. Remove snapshots tools."
        chroot /target apt-get autoremove --purge -y kaisen-btrfs-snapshots || true
fi

umount_fs

#Unhold kernel
chroot /target sh -c '/usr/bin/apt-mark showhold | while read kernel;do /usr/bin/apt-mark unhold $kernel;done' || true

#Readding executable bit of apt-btrfs-snapshot
if [ -e /target/usr/bin/apt-btrfs-snapshot ] && [ ! -x /target/usr/bin/apt-btrfs-snapshot ]; then
	chmod +x /target/usr/bin/apt-btrfs-snapshot
fi
