#!/bin/sh

#Remove unnecessary guests additions preinstalled
if [ -x /target/usr/bin/systemd-detect-virt ]; then

SYSTEMD_CHECK=$(chroot /target systemd-detect-virt || true)
SYS_CHECK=$(cat /sys/class/dmi/id/sys_vendor | cut -d' ' -f1)

mount_fs() {
                mount --bind /sys /target/sys
                mount --bind /proc /target/proc
                mount --bind /dev /target/dev
                mount --bind /dev/pts /target/dev/pts
}

umount_fs() {
                umount /target/sys
                umount /target/proc
                umount /target/dev/pts
}

mount_fs

if [ $SYSTEMD_CHECK = vmware ]; then
	echo "Hypervisor detected: $SYSTEMD_CHECK. Removal of all other guest additions."
	in-target apt-get autoremove --purge -y virtualbox-guest-utils virtualbox-guest-x11 xserver-xorg-video-qxl qemu-guest-agent spice-vdagent spice-webdavd hyperv-daemons || true
	in-target systemctl enable open-vm-tools vgauth

elif [ $SYS_CHECK = innotek ]; then
	echo "Hypervisor detected: $SYS_CHECK (VirtualBox). Removal of all other guest additions."
	in-target apt-get autoremove --purge -y open-vm-tools open-vm-tools-desktop open-vm-tools-containerinfo open-vm-tools-salt-minion open-vm-tools-sdmp xserver-xorg-video-qxl qemu-guest-agent spice-vdagent spice-webdavd hyperv-daemons || true
	in-target systemctl enable virtualbox-guest-utils

elif [ $SYS_CHECK = QEMU ]; then
	echo "Hypervisor detected: $SYS_CHECK. Removal of all other guest additions."
	in-target apt-get autoremove --purge -y virtualbox-guest-utils virtualbox-guest-x11 open-vm-tools open-vm-tools-desktop open-vm-tools-containerinfo open-vm-tools-salt-minion open-vm-tools-sdmp hyperv-daemons || true
	in-target systemctl enable spice-vdagentd.service spice-vdagentd.socket spice-webdavd.service qemu-guest-agent.service

elif [ $SYSTEMD_CHECK = microsoft ]; then
	echo "Hypervisor detected: $SYSTEMD_CHECK. Removal of all other guest additions."
	in-target apt-get autoremove --purge -y virtualbox-guest-utils virtualbox-guest-x11 open-vm-tools open-vm-tools-desktop open-vm-tools-containerinfo open-vm-tools-salt-minion open-vm-tools-sdmp xserver-xorg-video-qxl qemu-guest-agent spice-vdagent spice-webdavd || true

elif [ $SYSTEMD_CHECK = none ] || [ $SYSTEMD_CHECK = zvm ] || [ $SYSTEMD_CHECK = powervm ] || [ $SYSTEMD_CHECK = xen ] || [ $SYSTEMD_CHECK = bochs ] || [ $SYSTEMD_CHECK = uml ] || [ $SYSTEMD_CHECK = parallels ] || [ $SYSTEMD_CHECK = bhyve ] || [ $SYSTEMD_CHECK = qnx ] || [ $SYSTEMD_CHECK = acrn ]; then
	echo "No hypervisor detected with preinstalled guest additions. Deletion of all guest additions."
	in-target apt-get autoremove --purge -y virtualbox-guest-utils virtualbox-guest-x11 open-vm-tools open-vm-tools-desktop open-vm-tools-containerinfo open-vm-tools-salt-minion open-vm-tools-sdmp xserver-xorg-video-qxl qemu-guest-agent spice-vdagent spice-webdavd hyperv-daemons || true
fi
fi

#Add the created user to the vboxusers group if it exists
VBOXUSERS_GROUP=$(chroot /target grep -o vboxusers /etc/group || true)
if [ $VBOXUSERS_GROUP = vboxusers 2> /dev/null ]; then
	echo "The vboxusers group exist. Adding the created user in this group..."
	for user in $(awk -F: '/\/home/ {printf "%s:%s\n",$1,$3}' /target/etc/passwd | cut -d: -f1)
	do
		in-target usermod -a -G vboxusers "$user" || true
	done
	echo "Done"
fi

#Add the created user to the vboxsf group if it exists
VBOXSF_GROUP=$(chroot /target grep -o vboxsf /etc/group || true)
if [ $VBOXSF_GROUP = vboxsf 2> /dev/null ]; then
	echo "The vboxsf group exist. Adding the created user in this group..."
        for user in $(awk -F: '/\/home/ {printf "%s:%s\n",$1,$3}' /target/etc/passwd | cut -d: -f1)
        do
                in-target usermod -a -G vboxsf "$user" || true
        done
	echo "Done"
fi

#Check if / use BTRFS as filesystem to remove kaisen-btrfs-snapshots if BTRFS not use
CHECK_ROOTFS=$(grep -v -E "^(#|$)" /target/etc/fstab | grep -v /bin | grep -v /boot | grep -v /etc | grep -v /home | grep -v /lib | grep -v /media | grep -v /mnt | grep -v /opt | grep -v /root | grep -v /run | grep -v /sbin | grep -v /srv | grep -v /tmp | grep -v /usr | grep -v /var | grep -o btrfs || true)
CHECK_FSTAB=$(grep -v -E "^(#|$)" /target/etc/fstab | grep -v /bin | grep -v /boot | grep -v /etc | grep -v /home | grep -v /lib | grep -v /media | grep -v /mnt | grep -v /opt | grep -v /root | grep -v /run | grep -v /sbin | grep -v /srv | grep -v /tmp | grep -v /usr | grep -v /var | grep -o subvol=@ || true)
CHECK_SUBVOL=$(chroot /target btrfs subvolume list / 2> /dev/null | chroot /target grep -o @ 2> /dev/null || true)

if [ $CHECK_ROOTFS = btrfs 2> /dev/null ] && [ $CHECK_FSTAB = "subvol=@" 2> /dev/null ] && [ $CHECK_SUBVOL = @ 2> /dev/null ]; then
	echo "BTRFS is the filesystem use for the / partition, and the / partition is mount in the @ subvolume. Installation of the BTRFS snapshots tools..."
	in-target apt-get install -y kaisen-btrfs-snapshots || true
	#Force the activation of BTRFS quota
	in-target btrfs quota enable /
	in-target btrfs quota enable /home
else
	echo "BTRFS is not use for the / partition or the / partition isn't mounted in the @ subvolume. No action is required."
fi

#Update the files database for the plocate command
if [ -x /target/usr/bin/updatedb ]; then
        in-target updatedb
fi

umount_fs

#Unhold kernel
chroot /target sh -c '/usr/bin/apt-mark showhold | while read kernel;do /usr/bin/apt-mark unhold $kernel;done' || true
